
import { GoogleGenAI } from "@google/genai";
import { PROMPT_TEMPLATE } from "../constants";

export const generateOrnamentImage = async (
  logoBase64: string,
  logoMimeType: string,
  companyName: string
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  // The API expects base64 data without the data:image/xxx;base64, prefix
  const cleanBase64 = logoBase64.split(',')[1] || logoBase64;
  
  const prompt = PROMPT_TEMPLATE(companyName);

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: cleanBase64,
              mimeType: logoMimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
        }
      }
    });

    if (!response.candidates || response.candidates.length === 0) {
      throw new Error("No image generated by the AI.");
    }

    // Iterate parts to find the image
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }

    throw new Error("The AI response did not contain an image part.");
  } catch (error: any) {
    console.error("Gemini Generation Error:", error);
    if (error.message?.includes("Requested entity was not found")) {
      throw new Error("API configuration error. Please ensure your project settings are correct.");
    }
    throw error;
  }
};
