
import { GoogleGenAI } from "@google/genai";
import { IMAGE_PROMPT_TEMPLATE } from "../constants";

export const isGeminiConfigured = (): boolean => !!process.env.GEMINI_API_KEY?.trim();

// Gemini's image model rejects image/svg+xml as an unsupported input MIME type. Rasterize
// SVG logos to PNG (client-side, via canvas) before sending.
const rasterizeIfSvg = (dataUrl: string, mimeType: string): Promise<{ dataUrl: string; mimeType: string }> => {
  if (!mimeType.includes("svg")) {
    return Promise.resolve({ dataUrl, mimeType });
  }

  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.width || 512;
      canvas.height = img.height || 512;
      const ctx = canvas.getContext("2d");
      if (!ctx) {
        reject(new Error("Canvas is not supported in this browser."));
        return;
      }
      ctx.fillStyle = "#ffffff";
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
      resolve({ dataUrl: canvas.toDataURL("image/png"), mimeType: "image/png" });
    };
    img.onerror = () => reject(new Error("Couldn't read the uploaded SVG logo."));
    img.src = dataUrl;
  });
};

export const generateOrnamentImage = async (
  logoBase64: string,
  logoMimeType: string,
  companyName: string
): Promise<string> => {
  const apiKey = process.env.GEMINI_API_KEY?.trim();
  if (!apiKey) {
    throw new Error("Gemini API key is missing. Please set GEMINI_API_KEY in .env.");
  }

  const { dataUrl, mimeType } = await rasterizeIfSvg(logoBase64, logoMimeType);

  const ai = new GoogleGenAI({ apiKey });

  // The API expects base64 data without the data:image/xxx;base64, prefix
  const cleanBase64 = dataUrl.split(',')[1] || dataUrl;

  const prompt = IMAGE_PROMPT_TEMPLATE(companyName);

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: cleanBase64,
            mimeType,
          },
        },
        {
          text: prompt,
        },
      ],
    },
    config: {
      imageConfig: {
        aspectRatio: "1:1",
      }
    }
  });

  if (!response.candidates || response.candidates.length === 0) {
    throw new Error("No image generated by the AI.");
  }

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error("The AI response did not contain an image part.");
};
